// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: cache.proto

package cachegrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CacheServerClient is the client API for CacheServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CacheServerClient interface {
	GetClientID(ctx context.Context, in *AssignClientID, opts ...grpc.CallOption) (*AssignedClientID, error)
	SetItem(ctx context.Context, in *SetItemParams, opts ...grpc.CallOption) (*SetItemResult, error)
	GetItem(ctx context.Context, in *GetItemParams, opts ...grpc.CallOption) (*GetItemResult, error)
	SubscribeItem(ctx context.Context, in *GetItemParams, opts ...grpc.CallOption) (CacheServer_SubscribeItemClient, error)
}

type cacheServerClient struct {
	cc grpc.ClientConnInterface
}

func NewCacheServerClient(cc grpc.ClientConnInterface) CacheServerClient {
	return &cacheServerClient{cc}
}

func (c *cacheServerClient) GetClientID(ctx context.Context, in *AssignClientID, opts ...grpc.CallOption) (*AssignedClientID, error) {
	out := new(AssignedClientID)
	err := c.cc.Invoke(ctx, "/cachegrpc.CacheServer/GetClientID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServerClient) SetItem(ctx context.Context, in *SetItemParams, opts ...grpc.CallOption) (*SetItemResult, error) {
	out := new(SetItemResult)
	err := c.cc.Invoke(ctx, "/cachegrpc.CacheServer/SetItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServerClient) GetItem(ctx context.Context, in *GetItemParams, opts ...grpc.CallOption) (*GetItemResult, error) {
	out := new(GetItemResult)
	err := c.cc.Invoke(ctx, "/cachegrpc.CacheServer/GetItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServerClient) SubscribeItem(ctx context.Context, in *GetItemParams, opts ...grpc.CallOption) (CacheServer_SubscribeItemClient, error) {
	stream, err := c.cc.NewStream(ctx, &CacheServer_ServiceDesc.Streams[0], "/cachegrpc.CacheServer/SubscribeItem", opts...)
	if err != nil {
		return nil, err
	}
	x := &cacheServerSubscribeItemClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CacheServer_SubscribeItemClient interface {
	Recv() (*GetItemResult, error)
	grpc.ClientStream
}

type cacheServerSubscribeItemClient struct {
	grpc.ClientStream
}

func (x *cacheServerSubscribeItemClient) Recv() (*GetItemResult, error) {
	m := new(GetItemResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CacheServerServer is the server API for CacheServer service.
// All implementations must embed UnimplementedCacheServerServer
// for forward compatibility
type CacheServerServer interface {
	GetClientID(context.Context, *AssignClientID) (*AssignedClientID, error)
	SetItem(context.Context, *SetItemParams) (*SetItemResult, error)
	GetItem(context.Context, *GetItemParams) (*GetItemResult, error)
	SubscribeItem(*GetItemParams, CacheServer_SubscribeItemServer) error
	mustEmbedUnimplementedCacheServerServer()
}

// UnimplementedCacheServerServer must be embedded to have forward compatible implementations.
type UnimplementedCacheServerServer struct {
}

func (UnimplementedCacheServerServer) GetClientID(context.Context, *AssignClientID) (*AssignedClientID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientID not implemented")
}
func (UnimplementedCacheServerServer) SetItem(context.Context, *SetItemParams) (*SetItemResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetItem not implemented")
}
func (UnimplementedCacheServerServer) GetItem(context.Context, *GetItemParams) (*GetItemResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedCacheServerServer) SubscribeItem(*GetItemParams, CacheServer_SubscribeItemServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeItem not implemented")
}
func (UnimplementedCacheServerServer) mustEmbedUnimplementedCacheServerServer() {}

// UnsafeCacheServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CacheServerServer will
// result in compilation errors.
type UnsafeCacheServerServer interface {
	mustEmbedUnimplementedCacheServerServer()
}

func RegisterCacheServerServer(s grpc.ServiceRegistrar, srv CacheServerServer) {
	s.RegisterService(&CacheServer_ServiceDesc, srv)
}

func _CacheServer_GetClientID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignClientID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServerServer).GetClientID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cachegrpc.CacheServer/GetClientID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServerServer).GetClientID(ctx, req.(*AssignClientID))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheServer_SetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItemParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServerServer).SetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cachegrpc.CacheServer/SetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServerServer).SetItem(ctx, req.(*SetItemParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheServer_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServerServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cachegrpc.CacheServer/GetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServerServer).GetItem(ctx, req.(*GetItemParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheServer_SubscribeItem_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetItemParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CacheServerServer).SubscribeItem(m, &cacheServerSubscribeItemServer{stream})
}

type CacheServer_SubscribeItemServer interface {
	Send(*GetItemResult) error
	grpc.ServerStream
}

type cacheServerSubscribeItemServer struct {
	grpc.ServerStream
}

func (x *cacheServerSubscribeItemServer) Send(m *GetItemResult) error {
	return x.ServerStream.SendMsg(m)
}

// CacheServer_ServiceDesc is the grpc.ServiceDesc for CacheServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CacheServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cachegrpc.CacheServer",
	HandlerType: (*CacheServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClientID",
			Handler:    _CacheServer_GetClientID_Handler,
		},
		{
			MethodName: "SetItem",
			Handler:    _CacheServer_SetItem_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _CacheServer_GetItem_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeItem",
			Handler:       _CacheServer_SubscribeItem_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cache.proto",
}
